###
#
# Browse Books
#
GET http://localhost:4004/odata/v4/catalog/Books?
  # &$select=title,stock
  # &$expand=currency
  # &sap-language=de

###
#
# Get Author wit ID 101
#
GET http://localhost:4004/odata/v4/catalog/Authors

###
#
# Update Author with ID 101
#
POST http://localhost:4004/odata/v4/catalog/Authors
Content-Type: application/json

{"ID": 123, "name": "Some Author"}



###
#
# Order a Book
#
POST http://localhost:4004/odata/v4/catalog/Orders
Content-Type: application/json;IEEE754Compatible=true

{"book_ID": 201, "amount": 1}

###
#
# add a book
#
POST http://localhost:4004/odata/v4/catalog/Books
Content-Type: application/json

{"ID": 249, "title": "Thần Sấm", "author": {"ID": 150}, "stock": 111}

###
#
# alter a book
#
PATCH  http://localhost:4004/odata/v4/catalog/Books(249)
Content-Type: application/json

{ "title": "Move" }

###
#
# delete a book
#
DELETE http://localhost:4004/odata/v4/catalog/Books(249)
###
#
# test on
#
POST http://localhost:4004/odata/v4/catalog/hello(to='world')
Content-Type: application/json

{ "title": "Move" }
